@param String error

<!DOCTYPE html>
<html lang="en" >
<head>
  <meta charset="UTF-8">
  <title>${error}</title>
  <link rel='stylesheet' href='https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/3.3.7/css/bootstrap.min.css'>
<link rel='stylesheet' href='https://fonts.googleapis.com/css?family=Arvo'><link rel="stylesheet" href="/css/style.css">

</head>
<body>
<!-- partial:index.partial.html -->
<section class="page_404">
	<div class="container">
		<div class="row">	
		<div class="col-sm-12 ">
		<div class="col-sm-10 col-sm-offset-1  text-center">
		<div class="four_zero_four_bg">
			<h1 class="text-center ">${error}</h1>
		
		
		</div>
		
		<div class="contant_box_404">
		<h3 class="h2">
		Parece que você está perdido. 
		</h3>
		
		<p>${error} : a página que você está procurando não está disponivel!</p>
		
		<a href="/" class="link_404">Home</a>
	</div>
		</div>
		</div>
		</div>
	</div>
</section>
<!-- partial -->
  
</body>
</html>
