<!DOCTYPE html>
<html lang="pt-BR">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Sustância - Pesquisa de Campo</title>
    <link rel="stylesheet" href="/css/pagInicial.css">
</head>
<body>

<!-- Seção Banner -->
<section class="banner">
    <div class="conteudo">
        <div class="texto">
            <div class="circulo">
            </div>
            <h1>Para uma alimentação melhor, comece com
                <span class="carrossel-container">
                        <span class="carrossel">
                            <span class="palavra black">a Sustância.</span>
                            <span class="palavra">o Café da Manhã.</span>
                            <span class="palavra">o Almoço.</span>
                            <span class="palavra">o Lanche.</span>
                            <span class="palavra">o Jantar.</span>
                            <span class="palavra">a Ceia.</span>
                        </span>
                    </span>
            </h1>
            <p>Alimentando pesquisas, promovendo saúde.</p>
            <a href="/home" class="botao">Dê inicio a sua Experiência</a>
        </div>
        <div class="imagem">
            <img src="/assets/icons/prato-saudável.svg" alt="Tigela de frutas">
        </div>
    </div>
    <!-- Importando o JavaScript separado -->
    <script src="/js/pag-inicial.js"></script>
 </section>
</body>
</html>
